### ISSUE TITLE
" 7:30: not well-formed (invalid token)"

### ISSUE THREAD

**Issue by chachunc** [rhaleblian/dslibris#21]
After opening a few epubs succesfully, the ds turns off. when trying to open it again it just says " 7:30: not well-formed (invalid token)"...   replacing the files makes it useable again

**Comment by rhaleblian** [comment]
Does the file `dslibris.log` get written to your storage?

**Comment by chachunc** [comment]
yes

**Comment by chachunc** [comment]
[dslibris.log](https://github.com/rhaleblian/dslibris/files/5757577/dslibris.log)
sorry, had to look for my usb adapter. here's the log file

**Comment by chachunc** [comment]
so, is there a fix for this? i really want to use it

**Comment by chachunc** [comment]
just tried changing things around a bit and found out that after replacing the .XML file it works again. i always replaced XML and .ds  so I just thought replacing the ds file was making it work again

**Comment by chachunc** [comment]
also, this only happens after opening a book. when I just restart it without opening a book, it works fine

**Comment by chachunc** [comment]
I fixed it! One of my books had an "&" symbol in the filename, once i took it out and changed the filename in the .xml file, it worked again without problem!

**Comment by rhaleblian** [comment]
Nice! '&' is a legal character to use in Windows (NTFS) but i don't know if FAT ever allowed it.
