### ISSUE TITLE
Default font doesn't load

### ISSUE THREAD

**Issue by rhaleblian** [rhaleblian/dslibris#22]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rhaleblian** [comment]
Hi when I open the nds file I get this error:
$ dslibris
progr: filesystem mounted.
progr: read prefs, bookdir is '/
book/' .
fatal: font not found (2)
I have all the fonts in the font folder? And I didnt do anything but it doesnt want to work. Am I doing something wrong?

**Comment by rhaleblian** [comment]
Show me the exaect content of the /font folder?

**Comment by ndsgamer4654** [comment]
> Show me the exact content of the /font folder?

DejaVuLGCSerif
DejaVuLGCSerif-Bold
DejaVuLGCSerif-BoldItalic
DejaVuLGCSerifCondensed
DejaVuLGCSerifCondensed-Bold
DejaVuLGCSerifCondensed-BoldItalic
DejaVuLGCSerifCondensed-Italic
DejaVuLGCSerif-Italic
DejaVuSans
DejaVuSans-Bold
DejaVuSans-BoldOblique
DejaVuSans-ExtraLight
DejaVuSans-Oblique
LiberationSans-Regular
LiberationSerif-Bold
LiberationSerif-BoldItalic
LiberationSerif-Italic
LiberationSerif-Regular

All of them are TrueType font files

**Comment by rhaleblian** [comment]
Looks correct.  LiberationSerif is the key set of fonts.
This has been reported before but any single cause was never nailed down.
If there is a 'dslibris.log' file in the root folder, attach it here.

**Comment by ndsgamer4654** [comment]
There is no dslibris.log file and the xml file isn't supported by GitHub

**Comment by rhaleblian** [comment]
If there's no log file i wonder if the formatting of the card is just a little weird. is is FAT, FAT32 or exFAT?

**Comment by rhaleblian** [comment]
side note to devs: to avoid long-names-on-FAT problems, consider renaming the default font back to an 8.3 name.

**Comment by rhaleblian** [comment]
starting to feel that this happened to me too once, and renaming the default font would possibly help.
when time permits @rhaleblian can make an alternate build and @ndsgamer4654 could try that out.
it should be tested against all flavours of FAT that users might use to format their microSD card.

**Comment by mwaitzman** [comment]
I'm getting this error too

**Comment by rhaleblian** [comment]
if you guys feel like experimenting, and can reformat your cards, reformat them with FAT or FAT32 and not exFAT.
i usually use Windows to do this.
then reinstall the dslibris files.

**Comment by rhaleblian** [comment]
bumping, as there is new content in the previous comment.

**Comment by ndsgamer4654** [comment]
Its FAT32 I use Twilight++ and it requires a FAT32 type formatting.

**Comment by rhaleblian** [comment]
another thing to try would be to remove `dslibris.xml` and let dslibris make a new one on next launch.

**Comment by ndsgamer4654** [comment]
Hey I tried letting dslibris make its own xml file. No difference. I also don't understand what you meant by naming the font to 8.3?
My card type is FAT32 i checked. Could this be a problem with DLDI patching since I am using it on a DSi XL with Twilight++?

**Comment by ndsgamer4654** [comment]
Hey another update I got it to work. I downloaded the zip file again. I think the mistake I was making was I was copying the whole folder to the root menu. I copied only the contents and if the dslibris-1.5.1 and it worked!! Thanks for all the help!

**Comment by rhaleblian** [comment]
Great.  Yes, the way everybody describe where to put zip file contents is often vague.  We should add some doc showing exactly what your SD card should look like.

**Comment by rhaleblian** [comment]
ps. '8.3' means a short name that DOS natively understands -- no more than 8 characters before the '.' and no more than 3 after it.

**Comment by rhaleblian** [comment]
@mwaitzman does your SD card have dslibris.nds in the root folder (not a subdirectory) with 'book' and 'font' right next to it?

-> dslibris.nds
-> book
-> font

**Comment by rhaleblian** [comment]
Not enough evidence that things need changing, but it would be nice to embed the mandatory fonts into nitrofs or otherwise make them available without depending on libfat.
