### ISSUE TITLE
dslibris Guide Book

### ISSUE THREAD

**Issue by Victini378** [rhaleblian/dslibris#34]
Why is there no _Guide Book_, in epub, as in README images? It might be helpful to have that _Guide Book_ handy

**Comment by rhaleblian** [comment]
What would it contain that isn't in the QuickStart document?

**Comment by Victini378** [comment]
I intend an epub of QuickStart document

**Comment by Victini378** [comment]
![image](https://user-images.githubusercontent.com/44738063/160878154-721a4ead-98cc-4c25-8b14-d01b801a6bd0.png)
as this
