### ISSUE TITLE
when opening dslibris it wont read any of my epub files in the book folder, comes up with could not read book (225) 

### ISSUE THREAD

**Issue by aster01d9** [rhaleblian/dslibris#35]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rhaleblian** [comment]
See if there is a file on the SD card called `dslibris.log` and post it here.

**Comment by rhaleblian** [comment]
closing for lack of data.
