### ISSUE TITLE
Font issue on 3DS / Universal Updater

### ISSUE THREAD

**Issue by es14n139** [rhaleblian/dslibris#36]
Installed dslibris on my 3DS via Universal Updater, attempted to launch the app three times via Twilight Menu.  Each time it failed to open and showed the log messages in the attached file.  font not found (2) was the error all three times.  I checked the font folder in the install and it had all the .tff files that dslibris.xml called for, so I'm not sure what happened.

**Additional context**
[dslibris.log](https://github.com/rhaleblian/dslibris/files/11638779/dslibris.log)

**Comment by rhaleblian** [comment]
That sucks.  What is Universal updater?

**Comment by es14n139** [comment]
Universal Updater is a homebrew software downloader and installer that can be run on the 3DS itself; it's supposed to make it easier to install homebrew than doing it manually.  That's where I found dslibris, it's listed there.  Since the install was done automatically by Universal Updater, I don't know if it performed the DLDI patch listed in the included install instructions, I don't know what that is myself either so I didn't do it manually.  Here's a link to the listing on their website:  https://db.universal-team.net/ds/dslibris

I did check for an font folder, and it did contain several ttf files.  The font folder in the install contains the following ttf files:
DejaVuLGCSerif
DejaVuLGCSerif-Bold
DejaVuLGCSerif-BoldItalic
DejaVuLGCSerifCondensed
DejaVuLGCSerifCondensed-Bold
DejaVuLGCSerifCondensed-BoldItalic
DejaVuLGCSerifCondensed-Italic
DejaVuLGCSerif-Italic
DejaVuSans
DejaVuSans-Bold
DejaVuSans-BoldOblique
DejaVuSans-ExtraLight
DejaVuSans-Oblique
LiberationSans-Regular
LiberationSerif-Bold
LiberationSerif-BoldItalic
LiberationSerif-Italic
LiberationSerif-Regular

Even after adding a bunch of additional ttf fonts from my Microsoft Office apps, it still gave the same error.

**Comment by rhaleblian** [comment]
I wonder how DLDI patching is being handled.  Without the proper patching, reading from the FAT filesystem will fail and you'll get exactly what you are experiencing.  The team maintaining should strive for a success report for `dslibris` (which means they understand what success is) and post it for everyone.

You have the required fonts, so that's good.  Check that they were put in the /fonts directory.  That directory has to be at the root of the filesystem of your card/device.

Let's keep this open even though we have ground to punt this to the Universal Updater et al for a statement about DLDI and FAT support.  I have heard little about successes on 3DS but I would like to see it.

**Comment by es14n139** [comment]
Ah, the font directory is not at the root of the SD card, but dslibris.xml is.  dslibris is installed in its own folder at the root of the sd card, so it would be root/dslibris/font.  Should I move the entire contents of the dslibris folder to the root of the SD card?  Attached is a zip file containing that folder, along with the associated xml and log files, which are at the root of the directory.
[dslibris (2).zip](https://github.com/rhaleblian/dslibris/files/11698218/dslibris.2.zip)
I will research how to do DLDI patching on my own so I can try to install dslibris manually.

**Comment by rhaleblian** [comment]
> Should I move the entire contents of the dslibris folder to the root of the SD card?

Yes.  You should have `book` and `font` folders at the root.  `dslibris.nds` is also at the root.
Sounds like time to allow this structure to be put in a folder.  It's quite a reasonable expectation.

**Comment by es14n139** [comment]
Alright, I'll see how it works.  I also just found out that the Mac version folder also got installed to my sd card.  Judging by how mangled the text file is, it seems like it shouldn't be here.  Attached below.
[__MACOSX.zip](https://github.com/rhaleblian/dslibris/files/11709548/__MACOSX.zip)

**Comment by es14n139** [comment]
After moving everything to the root, I was able to launch dslibris and open a basic text epub with it.  Thanks for the help.

**Comment by rhaleblian** [comment]
I'm glad DLDI patching didn't factor in.
