### ISSUE TITLE
Move support libraries to dkp-pacman

### ISSUE THREAD

**Issue by rhaleblian** [rhaleblian/dslibris#4]
Maybe poll the devkitPro forum to see if there's value in in the idea.

**Comment by WinterMute** [comment]
See https://devkitpro.org/wiki/devkitPro_pacman

Would be rather better if you were using latest tools and libraries rather than building old ones manually though. It's an utter pain in the neck when people turn up with frankenstein toolchains.

There have been requests for zlib at least for DS.

All the current PKGBUILDs are at https://github.com/devkitPro/pacman-packages

**Comment by rhaleblian** [comment]
These additional packages should be built and released in lockstep with the present-day devkitPro itself.

I'm forced to build older releases for this project since i'm out of time investigating why the FAT code here, which appears rather boilerplate, stops working for newer releases. I frankly regret the time spent getting old tools built, but I was adamant about getting this product working _somehow_. Water under the bridge. Somebody might want to take a stab the problem.

That's academic, though, as the idea is for a broader audience than merely this project. Is there a project which builds ubiquitous packages like zlib for release alongside devkitPro?

**Comment by rhaleblian** [comment]
BTW excellent work with the toolchain.

**Comment by rhaleblian** [comment]
Reopened #1.

**Comment by WinterMute** [comment]
> I'm forced to build older releases for this project since i'm out of time investigating why the FAT code here, which appears rather boilerplate, stops working for newer releases. I frankly regret the time spent getting old tools built, but I was adamant about getting this product working _somehow_. Water under the bridge. Somebody might want to take a stab the problem.

I've commented on the issue you re-opened. Hopefully the changes I made get you a little further along. 

> That's academic, though, as the idea is for a broader audience than merely this project. Is there a project which builds ubiquitous packages like zlib for release alongside devkitPro?

devkitPro is an organisation, not software. We have a whole bunch of "portlibs" packages we release for use with the tools via https://devkitpro.org/wiki/devkitPro_pacman. The repo I linked (https://github.com/devkitPro/pacman-packages) is where the PKGBUILD files for those packages are kept & we build & release those as libraries are added/updated.

**Comment by rhaleblian** [comment]
> devkitPro is an organisation, not software.
Alright, let's pretend i said "devkitARM".

**Comment by rhaleblian** [comment]
Progress here, courtesy @WinterMute
https://github.com/devkitPro/pacman-packages

**Comment by rhaleblian** [comment]
@rhaleblian now needs to remove the tool/ dir and point to dkp-pacman.

**Comment by rhaleblian** [comment]
Resolved via
https://github.com/rhaleblian/dslibris/pull/7
