### ISSUE TITLE
how to read japanese epubs

### ISSUE THREAD

**Issue by Elmagob99** [rhaleblian/dslibris#48]
hey guys, i really like the idea of my dsi xl being an epub reader, however i would like to seize the device  to read some japanese light novels here, i have tons of epubs.
I upload some japanese fonts in .ttf format but still the text is not showing up, any ideas?

**Comment by rhaleblian** [comment]
generally you did the right thing.  kana has worked before.
grab dslibris.log and try to post a zip of it here.

**Comment by rhaleblian** [comment]
oh you should go into prefs with the button in the books page and set the font too.
