### ISSUE TITLE
Test on DSi and DSi XL

### ISSUE THREAD

**Issue by rhaleblian** [rhaleblian/dslibris#5]
The original DS is pretty long in the tooth now.
Newer DSes have asymmetric screens that do not work well vertically.
The Switch might be interesting, but we again traipse along the border of a territory patrolled by a hardware vendor who is very particular about how their hardware is used.

**Comment by rhaleblian** [comment]
Silent George has some DSi s and he'll bring one in for me to try.

**Comment by Merith-TK** [comment]
version 1.4.9 works just fine for my DSi using HiyaCFW on an 8gb sdcard, a little long load time for large epub books, but otherwise flawless, 
I did change the font to opensans for me, but otherwise it is gud

**Comment by rhaleblian** [comment]
Thank for reporting that. Glad that the font change worked.
