### ISSUE TITLE
Double-buffered rendering

### ISSUE THREAD

**Issue by rhaleblian** [rhaleblian/dslibris#8]
**Is your feature request related to a problem? Please describe.**
Everything flashes all time.

**Describe the solution you'd like**
Don't flash so much.

**Describe alternatives you've considered**
Closing my eyes.

**Additional context**
My eyes already hurt enough, thank you.

**Comment by Merith-TK** [comment]
never had the thing flash on me, DSi, hiya CFW

**Comment by rhaleblian** [comment]
I haven't seen it in a while either.

**Comment by rhaleblian** [comment]
> I haven't seen it in a while either.
I _have_, but on 3DS it's less janky.

**Comment by AdrianGjonca** [comment]
Got full screen but it feels sluggish and janky when changing between app modes.
@rhaleblian Can you give it a spin and see what you think. I might need to work further on the rendering because I don't feel this is usable yet.

Also I don't even think it is possible to do hardware double buffering on both screens

**Comment by AdrianGjonca** [comment]
@rhaleblian I fixed this but I no longer have push access

**Comment by AdrianGjonca** [comment]
> No caching should be involved with double buffering. I am changing text rendering so I recommend you do not touch that.

Yes but I began to investigate why the screen was rendering so slow and I noticed it was the slow lookup of the glyph cache. Take a look what I did on my fork on the renderer-rewrite branch. 

Basically you had a hashmap leading to Cache objects which themselves only contained another hashmap. I switched to a single hashmap increasing the speed but causing bugs. Please take a look as the latency is absurdly jarring, especially on OG hardware.

**Comment by rhaleblian** [comment]
Moving your comment to the other issue.
